/*
-------------------------
COLONIAL LIBERATION FRONT
-------------------------
*/

/datum/skills/clf
	name = "Insurgent"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_CIVILIAN,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_DEFAULT,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_UNTRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_UNTRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_DEFAULT,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_ENDURANCE = SKILL_ENDURANCE_WEAK,
		SKILL_PILOT = SKILL_PILOT_UNTRAINED,
	)

/datum/skills/clf/combat_engineer
	name = "Insurgent Technician"
	skills = list(
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
	)

/datum/skills/clf/combat_medic
	name = "Insurgent Medic"
	skills = list(
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_SURGERY = SKILL_SURGERY_TRAINED,
	)

/datum/skills/clf/specialist
	name = "Insurgent Specialist"
	skills = list(
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_NOVICE, //to use c4
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_NOVICE,
	)

/datum/skills/clf/sniper
	name = "Insurgent Sniper"
	skills = list(
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
	)

/datum/skills/clf/leader
	name = "Insurgent Team Leader"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED, // to use C4
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
	)

/datum/skills/clf/commander
	name = "Insurgent Cell Commander"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER,
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_SMARTGUN,
	)

/*
------------------
CLF SPECIAL FORCES
------------------
*/

/datum/skills/clf_special_forces/regular
	name = "Insurgent Operative"
	skills = list(
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
	)

/datum/skills/clf_special_forces/regular/combat_engineer
	name = "Insurgent Operative Technician"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_MASTER,
		SKILL_VEHICLE = SKILL_VEHICLE_CREWMAN,
	)

/datum/skills/clf_special_forces/regular/combat_medic
	name = "Insurgent Operative Medic"
	skills = list(
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_SURGERY = SKILL_SURGERY_TRAINED,
	)

/datum/skills/clf_special_forces/regular/specialist
	name = "Insurgent Operative Specialist"
	skills = list(
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
	)

/datum/skills/clf_special_forces/regular/team_leader
	name = "Insurgent Operative Leader"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER,
		SKILL_CQC = SKILL_CQC_EXPERT,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_SURGERY = SKILL_SURGERY_NOVICE,
		SKILL_JTAC = SKILL_JTAC_MASTER,
		SKILL_INTEL = SKILL_INTEL_TRAINED,
		SKILL_PILOT = SKILL_PILOT_EXPERT,
	)

/*
------------------
CANC BROTHERHOOD OF THOUSAND PETALS
------------------
*/

/datum/skills/brotherhood
	name = "Brotherhood Operative"
	skills = list(
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_PILOT= SKILL_PILOT_EXPERT,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_CQC = SKILL_CQC_EXPERT,
		SKILL_INTEL = SKILL_INTEL_EXPERT,
		SKILL_VEHICLE = SKILL_VEHICLE_LARGE,
		SKILL_DOMESTIC = SKILL_DOMESTIC_MASTER,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
	)

/datum/skills/brotherhood/medic
	name = "Brotherhood Combat Medic"
	skills = list(
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_PILOT= SKILL_PILOT_EXPERT,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_CQC = SKILL_CQC_EXPERT,
		SKILL_INTEL = SKILL_INTEL_EXPERT,
		SKILL_VEHICLE = SKILL_VEHICLE_LARGE,
		SKILL_DOMESTIC = SKILL_DOMESTIC_MASTER,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
		SKILL_SURGERY = SKILL_SURGERY_TRAINED,
		SKILL_RESEARCH = SKILL_RESEARCH_TRAINED,
	)

/datum/skills/brotherhood/leader
	name = "Brotherhood Squad Leader"
	skills = list(
		SKILL_ENDURANCE = SKILL_ENDURANCE_MASTER,
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_PILOT= SKILL_PILOT_EXPERT,
		SKILL_POWERLOADER = SKILL_POWERLOADER_MASTER,
		SKILL_POLICE = SKILL_POLICE_SKILLED,
		SKILL_MEDICAL = SKILL_MEDICAL_TRAINED,
		SKILL_CQC = SKILL_CQC_EXPERT,
		SKILL_INTEL = SKILL_INTEL_EXPERT,
		SKILL_VEHICLE = SKILL_VEHICLE_LARGE,
		SKILL_DOMESTIC = SKILL_DOMESTIC_MASTER,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_ALL,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_SUPER,
		SKILL_EXECUTION = SKILL_EXECUTION_TRAINED,
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_JTAC = SKILL_JTAC_EXPERT,
	)
