/*
-------------------------
COLONIAL LIBERATION FRONT
-------------------------
*/

/datum/skills/clf_pve
	name = "Insurgent"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_NOVICE,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,

		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_JTAC = SKILL_JTAC_BEGINNER,

		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_PILOT = SKILL_PILOT_UNTRAINED,

		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_DEFAULT,

		SKILL_MEDICAL = SKILL_MEDICAL_DEFAULT,
		SKILL_ENDURANCE = SKILL_ENDURANCE_SURVIVOR,
	)

/datum/skills/clf_pve/combat_engineer
	name = "Insurgent Technician"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,

		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_LARGE,
		SKILL_PILOT = SKILL_PILOT_TRAINED,
	)

/datum/skills/clf_pve/combat_medic
	name = "Insurgent Medic"
	skills = list(
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,

		SKILL_MEDICAL = SKILL_MEDICAL_DOCTOR,
		SKILL_SURGERY = SKILL_SURGERY_TRAINED,
	)

/datum/skills/clf_pve/leader
	name = "Insurgent Team Leader"
	skills = list(
		SKILL_ENGINEER = SKILL_ENGINEER_ENGI,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,

		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_FIREMAN = SKILL_FIREMAN_SKILLED,
		SKILL_INTEL = SKILL_INTEL_TRAINED,
		SKILL_JTAC = SKILL_JTAC_TRAINED,

		SKILL_VEHICLE = SKILL_VEHICLE_LARGE,
		SKILL_PILOT = SKILL_PILOT_EXPERT,

		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_TRAINED,

		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
	)

/datum/skills/clf_pve/commander
	name = "Insurgent Cell Commander"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER,
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_SMARTGUN,
	)
